import { NAMESPACE } from '../constants';

export const HAS_REACHED_PAGE_BOTTOM = `${NAMESPACE}/ui/HAS_REACHED_PAGE_BOTTOM`;
export const HAS_PASSED_HEIGHT_THRESHOLD = `${NAMESPACE}/ui/HAS_PASSED_HEIGHT_THRESHOLD`;
export const SCROLL_ERROR = `${NAMESPACE}/ui/SCROLL_ERROR`;
