import { NAMESPACE } from '../constants';

export const ADD_PROXY_RESPONSE = `${NAMESPACE}/proxy/ADD_PROXY_RESPONSE`;
export const SET_PROXY_RESPONSE = `${NAMESPACE}/proxy/SET_PROXY_RESPONSE`;
export const FLASH_RESPONSE = `${NAMESPACE}/proxy/FLASH_RESPONSE`;
export const DELETE_PROXY_RESPONSE = `${NAMESPACE}/proxy/DELETE_PROXY_RESPONSE`;
export const PROXY_RESPONSE_DELETED = `${NAMESPACE}/proxy/PROXY_RESPONSE_DELETED`;
