import { NAMESPACE } from '../constants';

export const RESPONSE_LOGGED = `${NAMESPACE}/proxy/RESPONSE_LOGGED`;
export const RESPONSE_MOCKED = `${NAMESPACE}/proxy/RESPONSE_MOCKED`;
export const MOCK_RESPONSE = `${NAMESPACE}/proxy/MOCK_RESPONSE`;
export const MOCK_SERVED_RECENTLY = `${NAMESPACE}/proxy/MOCK_SERVED_RECENTLY`;
export const MOCK_SERVED_RECENTLY_CANCEL = `${NAMESPACE}/proxy/MOCK_SERVED_RECENTLY_CANCEL`;
export const DELETE_PROXY_RESPONSE = `${NAMESPACE}/proxy/DELETE_PROXY_RESPONSE`;
export const PROXY_RESPONSE_DELETED = `${NAMESPACE}/proxy/PROXY_RESPONSE_DELETED`;
